apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - flask-secret.yml
  - configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - NetworkPolicy.yml
  - allow-network-db.yml
  - flask-deployment.yaml
  - flask-service.yaml
  - flask-ingress.yml

configMapGenerator:
  - name: mysql-init-sql
    namespace: database-namespace
    files:
      - 01-queries.sql=queries.sql

generatorOptions:
  disableNameSuffixHash: true
